
# This file was *autogenerated* from the file test_for_sage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_10 = Integer(10)
stationary_points = lambda f : solve([gi for gi in f.gradient()], f.variables())
__tmp__=var("x,y,z"); f = symbolic_expression((sqrt(_sage_const_10 )*sqrt(x**_sage_const_2 +6y**_sage_const_2 +_sage_const_3 *z**_sage_const_2 )/(x + 6y + 3z)**_sage_const_2 )**_sage_const_2 ).function(x,y,z)
g=f(x,y,_sage_const_1 )
print stationary_points(g)

